### ISSUE TITLE
Hide play button when in vertical mode

### ISSUE THREAD

**Issue by reconman** [MathewSachin/Fate-Grand-Automata#518]
Just a new idea I came up with. When you stop the script for some reason and want to look something up outside of FGO, then you have to constantly move the play button around so you can type and click properly or you have to stop the service.

What if the play button is only shown in landscape mode, which is automatically started when FGO is in the foreground?

**Comment by MathewSachin** [comment]
#### TODO:

- [ ] Show the status with #379 instead of popping up the button on toggle service.
- [x] Make foreground service on Toggle Service and get Media Projection permission.
- [x] Foreground Service notification keeps showing even if PLAY button isn't visible.
- [ ] Show PLAY button only when any FGO is in the foreground.
